# jvm
org.gradle.jvmargs=-Dfile.encoding=UTF-8 --add-opens java.base/java.time=ALL-UNNAMED\
  --add-opens=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED \
  --add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED \
  --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED \
  --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED \
  --add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED \
  --add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED

# sonar
systemProp.sonar.projectName=fr-autotest-framework
systemProp.sonar.projectKey=fr-autotest-framework
systemProp.sonar.sourceEncoding=utf-8
systemProp.sonar.language=java
systemProp.sonar.java.source=11

# repositories
snapshotsRepoUrl=https://nexus-internal.headoffice.psbank.local/repository/at-maven-snapshot/
releasesRepoUrl=https://nexus-internal.headoffice.psbank.local/repository/at-maven-release/
atMavenGroupUrl=https://nexus-internal.headoffice.psbank.local/repository/at-maven-group/
mvnProxyUrl=https://nexus-external.psbnk.msk.ru/repository/maven-public/

# libraries versions
jUnitVersion=5.8.2
jUnitEngineVersion=1.8.2
lombokVersion=1.18.22
cucumberVersion=7.2.3
sonarVersion=2.7
spotlessVersion=6.3.0
apachePoiVersion=5.2.0
restAssuredVersion=4.5.1
allureVersion=2.17.3
jacksonVersion=2.13.1
kafkaVersion = 2.8.2
logbackVersion = 1.2.7

#gradle
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

#TODO delete
#systemProp.javax.net.ssl.trustStore=jssecacerts
