dependencies {
    api 'org.hibernate:hibernate-core:5.6.5.Final'
    testImplementation 'com.h2database:h2:2.1.210'
    api 'org.reflections:reflections:0.10.2'
    api project(":core:cucumber-core")
}

task cucumber(type: Test) {
    doFirst {
        environment "cucumber.filter.tags", "@OrmTesting"
    }
}

task componentTesting(type: Test) {
    useJUnitPlatform {
        if (project.hasProperty('stand')){
            if (findProperty('stand').toString().toLowerCase()=='vm'){
                includeTags '@FakeTag'
            } else{
                includeTags '@OrmSteps'
            }
        }
    }
}

spotless {
    sql {
        target fileTree('.') {
            include '**/*.sql'
            exclude '**/build/**', '**/build-*/**'
        }
        dbeaver()
    }
}