plugins {
    id 'java'
}

dependencies {
    api "com.codeborne:selenide-proxy:6.2.1"
    implementation 'com.github.valfirst.browserup-proxy:browserup-proxy-mitm:2.1.3'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}

test {
    useJUnitPlatform()
}