dependencies {
    testImplementation("org.mockito:mockito-inline:3.6.28")

    implementation 'org.slf4j:slf4j-api:1.7.33'

    api project(":core:cucumber-core")

    api "org.apache.poi:poi:${apachePoiVersion}"
    api "org.apache.poi:poi-ooxml:${apachePoiVersion}"
    api "org.apache.pdfbox:pdfbox:3.0.0-RC1"
    api "org.apache.commons:commons-csv:1.9.0"
    api "org.jxls:jxls:2.11.0"
    api "org.jxls:jxls-poi:2.11.0"

    implementation "org.projectlombok:lombok:${lombokVersion}"
    implementation "com.flipkart.zjsonpatch:zjsonpatch:0.4.4"
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"
}

task componentTesting(type: Test) {
    useJUnitPlatform {
        includeTags '@DocumentSteps'
    }
}